//Layout.jsx -Tudo que você coloca nele envolve todas as páginas, somente será colocado header e footer.
import "./globals.css";
import Header from "@/layout/header/Header";
import Footer from "@/layout/footer/Footer";

export const metadata = {
  title: "NextSolve Studio Vision",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body>
        <Header /> {/* Header */}
        {children} {/* Páginas renderizadas */}
        <Footer />
      </body>
    </html>
  );
}
