//Layout.jsx -Tudo que você coloca nele envolve todas as páginas, somente será colocado header e footer.
import "./globals.css";
import Header from "@/layout/header/Header";

export const metadata = {
  title: "NextSolve",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header /> {/* Header */}
        {children} {/* Páginas renderizadas */}
                   {/* Footer */}
      </body>
    </html>
  );
}
